### PR TITLE
Extend Travis CI testing

### PR DESCRIPTION
**Pull request by JohanEngelen**

### CODE REVIEW

**Comment by JohanEngelen** [comment]
@Shachar Improved the Travis testing. I can't merge this though. (apparently I don't have the rights, please use squash+rebase for a little cleaner history)
@wilzbach Is the DFLAGS env var picked up by the project tester? (if it's not: that's great! Don't want the project tester to be using `-w -de`, or do we?)

**Comment by wilzbach** [comment]
No, we only parse the scripts section.

**Comment by PetarKirov** [comment]
@JohanEngelen instead of using environment variables, I think it would be cleaner to use one or more custom build types in your `dub.json`: http://code.dlang.org/package-format?lang=json#build-types.

**Comment by JohanEngelen** [comment]
@ZombineDev but then it won't work well with the dlang project tester (because it'd be part of the `script` section)
@wilzbach OK great, so it'll work.

**Pull request merged**
